---
# Load variable file based on the OS type, or a default if not found.
- include_vars: "{{ item }}"
  with_items:
   - "{{ ansible_os_family }}.yml"
   - "all.yml"

- name: get local IPv4 address
  local_action: setup filter=ansible_default_ipv4
  register: local_ipv4_address

- name: ensure directory /var/www/site/vlad_aux/db_io exists
  file: path=/var/www/site/vlad_aux/db_io state=directory

- include: mysql.yml
