---
- name: get local IPv4 address
  local_action: setup filter=ansible_default_ipv4
  register: local_ipv4_address

- name: ensure directory /var/www/site/vlad_aux/db_io exists
  file: path=/var/www/site/vlad_aux/db_io state=directory

- include: debian_mysql.yml
  when: ansible_os_family == "Debian"

- include: redhat_mysql.yml
  when: ansible_os_family == "RedHat"