---
- name: set up directories (with logs directory)
  file: path={{ apache2_docroot }}/logs state=directory recurse=yes
  sudo: true

# Include the appropriate OS specific setups.
- include: debian_apache.yml
  when: ansible_os_family == "Debian"

- include: debian_apache_ssl.yml
  when: ansible_os_family == "Debian"

- include: redhat_apache.yml
  when: ansible_os_family == "RedHat"

- include: redhat_apache_ssl.yml
  when: ansible_os_family == "RedHat"

# Run some common tasks.
- name: symlink www directory from home directory
  file: src={{ apache2_docroot }} dest=/home/{{ user }}/www state=link

- name: set default login directory to be {{ apache2_docroot }}
  lineinfile: dest=/home/{{ user }}/.bashrc state=present line='cd {{ apache2_docroot }}'
  tags: apache2

- name: add apache2_user to dialout group
  user: name={{ apache2_user }} groups=dialout append=yes
  sudo: true