---
- name: install packages
  apt: pkg={{ item }} state=installed
  with_items:
    - memcached
    - php5-memcached
  sudo: true
  notify:
      - restart apache2

- name: config file
  template: src=memcached.conf.j2 dest=/etc/memcached.conf
  sudo: true

- name: config file for the PHP memcache extension
  template: src=php_apache2_memcached.ini.j2 dest=/etc/php5/apache2/conf.d/memcached.ini
  sudo: true
  notify:
    - restart apache2