---
- name: install packages
  apt: pkg={{ item }} state=installed
  with_items:
    - memcached
    - php5-memcached
  sudo: true
  notify:
      - restart apache2
  when: ansible_os_family == "Debian"

- name: install packages
  yum: pkg={{ item }} state=installed
  with_items:
    - memcached
    - php-pecl-memcached
  sudo: true
  notify:
      - restart httpd
  when: ansible_os_family == "RedHat" and php_version == '5.3'

- name: cnstall packages (php 5.4)
  yum: pkg={{ item }} state=installed
  with_items:
    - memcached
    - php54-pecl-memcached
  sudo: true
  notify:
      - restart httpd
  when: ansible_os_family == "RedHat" and php_version == '5.4'

- name: config file
  template: src=memcached.conf.j2 dest=/etc/memcached.conf
  sudo: true

- name: check, what PECL memcache is installed
  shell: pecl list | grep 'memcache\s' | wc -l
  register: pecl_memcache_installed

- debug: var=pecl_memcache_installed

- name: PECL library install
  shell: printf "yes\n" | pecl install memcache creates=/usr/lib/php5/20100525/memcache.so
  when: pecl_memcache_installed.stdout == '0' and ansible_os_family == "Debian"
  sudo: true
  notify:
    - restart apache2

- name: PECL library install
  shell: printf "yes\n" | pecl install memcache creates=/usr/lib64/php/modules/memcache.so
  when: pecl_memcache_installed.stdout == '0' and ansible_os_family == "Redhat"
  sudo: true
  notify:
    - restart httpd

- name: config file for the PHP memcache extension
  template: src=php_apache2_memcached.ini.j2 dest=/etc/php5/apache2/conf.d/memcached.ini
  sudo: true
  notify:
    - restart apache2
  when: ansible_os_family == "Debian"

- name: config file for the PHP memcache extension
  template: src=php_apache2_memcached.ini.j2 dest=/etc/php.d/memcached.ini
  sudo: true
  notify:
    - restart httpd
  when: ansible_os_family == "Redhat"