---
# Install and configure MailHog.
- name: Ensure mailhog install directory exists.
  file:
    path: "{{ mailhog_install_dir }}"
    owner: root
    group: root
    state: directory
    mode: 0755

- name: Download MailHog binary.
  get_url:
    url: "{{ mailhog_binary_url }}"
    dest: "{{ mailhog_install_dir }}/mailhog"
    owner: root
    group: root
    mode: 0755

- name: Copy mailhog init script into place.
  copy:
    src: mailhog
    dest: /etc/init.d/mailhog
    owner: root
    group: root
    mode: 0755

- name: Ensure mailhog is enabled and will start on boot.
  service: name=mailhog state=started enabled=yes

# Install and configure sSMTP.
- include: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'

- include: setup-Debian.yml
  when: ansible_os_family == 'Debian'

- name: Copy sSMTP configuration.
  template:
    src: ssmtp.conf.j2
    dest: /etc/ssmtp/ssmtp.conf
    owner: root
    group: root
    mode: 0644

# - name: Check if Gogs is running.
#   command: service gogs status
#   changed_when: false
#   register: gogs_status

# - name: Ensure Gogs is running.
#   shell: >
#     su -c "service gogs start" -s /bin/bash {{ gogs_user }}
#   when: "'running' not in gogs_status.stdout"
