---

- name: drupal install | copy Drupal installation scripts
  template:
    src="drupal{{ item }}_install.j2"
    dest="{{ apache2_docroot }}/drupal{{ item }}_install.sh"
  with_items:
    - 6
    - 7
    - 8
    - 8dev
  sudo: true

# Setting "mode" to 755 in the above template task appears to have no effect :(
- name: drupal install | set Drupal installation scripts to executable
  file: 
    path="{{ apache2_docroot }}/drupal{{ item }}_install.sh" 
    mode=755
  with_items:
    - 6
    - 7
    - 8
    - 8dev
  sudo: true

- name: drupal install | create drupal folder
  file:
    path={{ apache2_docroot }}/drupal
    state=directory
    owner={{ user }}
    group={{ user }}
    recurse=yes
