---
- name: install MailCatcher prerequisite packages
  apt: pkg={{ item }} state=installed
  with_items:
    - rubygems
    - libsqlite3-dev
    - ruby-dev
  sudo: true

- name: Install MailCatcher with rbenv
  command: bash -lc "gem install mailcatcher"

- name: change php apache sendmail_path setting
  lineinfile: dest=/etc/php5/apache2/php.ini regexp="^[#|;]?sendmail_path =" insertafter="^[#|;]?sendmail_path =" line="sendmail_path = /usr/bin/env catchmail"
  when: php_install is defined and php_install == "y"
  sudo: true
  notify:
    - restart apache2

- name: change php cli sendmail_path setting
  lineinfile: dest=/etc/php5/cli/php.ini regexp="^[#|;]?sendmail_path =" insertafter="^[#|;]?sendmail_path =" line="sendmail_path = /usr/bin/env catchmail"
  when: php_install is defined and php_install == "y"
  sudo: true

- name: kill mailcatcher
  command: curl -s -i -v -X DELETE http://127.0.0.1:1080
  ignore_errors: yes
  register: kill_mailcatcher
  failed_when: "kill_mailcatcher.rc != 0"
  changed_when: False
  sudo: true

- name: run MailCatcher with no ip address restrictions
  command: bash -lc "mailcatcher --ip=0.0.0.0"
  register: run_mailcatcher
  failed_when: "run_mailcatcher.rc != 0"
  changed_when: False