---
- name: get pimpmylog package
  git: repo=https://github.com/potsky/PimpMyLog.git dest=/var/www/pimpmylog depth=1
  sudo: true

- name: add vhost for pimpmylog to sites-available folder
  template: src=apache_pimpmylog_vhost.j2 dest=/etc/apache2/sites-available/logs.{{ webserver_hostname }}.conf
  sudo: true
  when: ansible_os_family == "Debian"
  notify:
    - restart apache2

- name: enable the pimpmylog site
  command: a2ensite logs.{{ webserver_hostname }}.conf creates=/etc/apache2/sites-enabled/logs.{{ webserver_hostname }}.conf
  sudo: true
  when: ansible_os_family == "Debian"
  notify:
    - restart apache2

- name: ensure Pimpmylog directory permissions
  file: path=/var/www/pimpmylog mode=0777 state=directory recurse=yes
  sudo: true

- name: add configuration file
  copy: src=config.user.json dest=/var/www/pimpmylog/config.user.json
  sudo: true