---
- hosts: all
  vars_files:
    - "./vars/defaults/vagrant.yml"
    - "./vars/defaults/general.yml"
    - "./vars/defaults/install.yml"
    - [ "../../../settings/vlad-settings.yml", "../settings.yml", "vars/dummy-settings.yml" ]
    - [ "../../../settings/vlad-custom-settings.yml", "../../../vlad-custom/vars/main.yml" ]

  roles:
    - { role: vlad-custom, when: "custom_provision" }

  handlers:
    - include: common/handlers/main.yml
