---
- name: install ImageMagick
  apt: pkg=imagemagick
  when: ansible_os_family == "Debian"
  sudo: yes

- name: install ImageMagick
  yum: pkg={{ item }} state=installed
  when: ansible_os_family == "RedHat"
  sudo: true
  with_items:
    - ImageMagick
    - ImageMagick-devel