---
# Pantheon Import settings

vlad_pantheon_import_site: false
vlad_pantheon_import_site_email: ''
vlad_pantheon_import_site_password: ''
vlad_pantheon_import_site_site: ''
vlad_pantheon_import_site_env: ''
vlad_pantheon_import_site_include_code: false
vlad_pantheon_import_site_include_db: true
vlad_pantheon_import_site_include_files: true

# @todo: Figure out an easy way, or document an Ansible command — possibly with tags — to update the imported Pantheon site without having to rebuild the entire VM.
