---
- name: create adminer directory
  file: path=/var/www/adminer state=directory
  sudo: true

- name: copy adminer
  copy: src=adminer-3.7.1-en.php dest=/var/www/adminer/adminer-3.7.1-en.php
  sudo: true

- name: copy adminer stylesheet
  copy: src=adminer.css dest=/var/www/adminer/adminer.css
  sudo: true

- name: copy index.php configuration file into place
  template: src=index.j2 dest=/var/www/adminer/index.php
  sudo: true

- name: ensure adminer directory permissions
  file: path=/var/www/adminer mode=0777 recurse=yes
  sudo: true

- name: add vhost for adminer
  template: src=apache_adminer_vhost.j2 dest=/etc/apache2/sites-available/adminer.{{ webserver_hostname }}.conf
  sudo: true
  notify:
    - restart apache2

- name: enable the adminer site
  command: a2ensite adminer.{{ webserver_hostname }}.conf creates=/etc/apache2/sites-enabled/adminer.{{ webserver_hostname }}.conf
  sudo: true
  when: ansible_os_family == "Debian"
  notify:
    - restart apache2