---
- include: debian_php.yml
  when: ansible_os_family == "Debian"

- include: redhat_php.yml
  when: ansible_os_family == "RedHat"

- include: composer.yml

- include: pear.yml
- include: drush.yml
- include: drupal_install.yml

- include: debian_phing.yml
  when: ansible_os_family == "Debian"

- include: redhat_phing.yml
  when: ansible_os_family == "RedHat"

- include: debian_xdebug.yml
  when: ansible_os_family == "Debian"

- include: redhat_xdebug.yml
  when: ansible_os_family == "RedHat"