---
- name: pear | force upgrade of pear
  command: pear upgrade pear
  register: pear_upgrade_pear
  changed_when: "'Nothing to upgrade' not in pear_upgrade_pear.stdout"
  tags: pear
  sudo: true

- name: pear | update all channels
  command: pear update-channels
  tags: pear
  changed_when: false
  sudo: true

- name: pear | ensure pear is set to install stable packages
  command: pear config-set preferred_state stable
  tags: pear
  changed_when: false
  sudo: true

- name: pear | clear pear cache
  command: pear clear-cache
  changed_when: false
  tags: pear
  sudo: true